# Generated by Django 5.2.14 on 2026-05-14 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], max_length=10)),
                ('duration', models.PositiveIntegerField(help_text='Number of days')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('max_group', models.PositiveIntegerField(default=12)),
                ('region', models.CharField(choices=[('everest', 'Everest Region'), ('annapurna', 'Annapurna Region'), ('langtang', 'Langtang Region'), ('manaslu', 'Manaslu Region'), ('other', 'Other')], max_length=20)),
                ('cover_image', models.ImageField(upload_to='treks/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(limit_choices_to={'role': 'agency'}, on_delete=django.db.models.deletion.CASCADE, related_name='treks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
