# Generated by Django 5.2.14 on 2026-05-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0002_alter_trek_cover_image_alter_trek_price_trekimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trekimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='trekimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='treks/gallery/'),
        ),
    ]
