# Generated by Django 5.2.14 on 2026-05-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0003_trekimage_image_url_alter_trekimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trekimage',
            old_name='image',
            new_name='upload',
        ),
        migrations.AlterField(
            model_name='trekimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
