# Generated by Django 5.2.14 on 2026-05-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0004_rename_image_trekimage_upload_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trekimage',
            old_name='upload',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='trekimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
